--
-- Script was generated by Devart dbForge Studio for MySQL, Version 7.1.31.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2017/9/9 1:20:18
-- Server version: 5.5.5-10.2.7-MariaDB
-- Client version: 4.1
--


-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

-- 
-- Set default database
--
USE adminltemy;


--
-- Definition for table sys_activiti
--
DROP TABLE IF EXISTS sys_activiti;
CREATE TABLE sys_activiti (
  sys_activiti_id VARCHAR(255) NOT NULL DEFAULT '''''' COMMENT '主键',
  sys_activiti_pid VARCHAR(255) DEFAULT 'NULL' COMMENT '父主键',
  sys_activiti_name VARCHAR(50) DEFAULT 'NULL' COMMENT '名称',
  sys_activiti_task_key VARCHAR(255) DEFAULT 'NULL' COMMENT '流程id/节点id',
  sys_activiti_task_name VARCHAR(50) DEFAULT 'NULL' COMMENT '流程名称/节点名称',
  PRIMARY KEY (sys_activiti_id)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 4096
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table sys_area
--
DROP TABLE IF EXISTS sys_area;
CREATE TABLE sys_area (
  sys_area_id VARCHAR(255) NOT NULL COMMENT '主键',
  sys_area_pid VARCHAR(255) DEFAULT 'NULL' COMMENT '父主键',
  sys_area_name VARCHAR(255) DEFAULT 'NULL' COMMENT '地址名称',
  PRIMARY KEY (sys_area_id)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '用户所在地表'
ROW_FORMAT = DYNAMIC;

--
-- Definition for table sys_buy
--
DROP TABLE IF EXISTS sys_buy;
CREATE TABLE sys_buy (
  sys_buy_id VARCHAR(255) BINARY NOT NULL COMMENT '购买主键',
  sys_user_id VARCHAR(255) BINARY DEFAULT 'NULL' COMMENT '购买人',
  sys_goods_id VARCHAR(255) BINARY DEFAULT 'NULL' COMMENT '购买商品',
  sys_buy_price VARCHAR(255) BINARY DEFAULT 'NULL' COMMENT '购买价格',
  sys_buy_count VARCHAR(255) BINARY DEFAULT 'NULL' COMMENT '购买数量',
  sys_buy_time VARCHAR(255) BINARY DEFAULT 'NULL' COMMENT '购买时间',
  sys_buy_succ_d VARCHAR(255) BINARY DEFAULT 'NULL' COMMENT '成功状态:0_不成功,1_成功',
  sys_buy_createdate DATETIME DEFAULT NULL COMMENT '创建时间',
  sys_buy_updatedate DATETIME DEFAULT NULL COMMENT '更新时间',
  sys_buy_createuid VARCHAR(255) BINARY DEFAULT 'NULL' COMMENT '创建人id',
  sys_buy_updateuid VARCHAR(255) BINARY DEFAULT 'NULL' COMMENT '修改人id',
  PRIMARY KEY (sys_buy_id)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_bin
COMMENT = '购买管理'
ROW_FORMAT = DYNAMIC;


--
-- Definition for table sys_dict
--
DROP TABLE IF EXISTS sys_dict;
CREATE TABLE sys_dict (
  sys_dict_id VARCHAR(255) NOT NULL COMMENT '主键',
  sys_dict_pid VARCHAR(255) DEFAULT 'NULL' COMMENT '父主键',
  sys_dict_name VARCHAR(255) DEFAULT 'NULL' COMMENT '数据名称',
  sys_dict_value VARCHAR(255) DEFAULT 'NULL' COMMENT 'value值',
  sys_dict_seq INT(4) DEFAULT NULL COMMENT '排序',
  sys_dict_active VARCHAR(255) DEFAULT 'NULL' COMMENT '有效性',
  sys_dict_createdate DATETIME DEFAULT NULL COMMENT '创建时间',
  sys_dict_updatedate DATETIME DEFAULT NULL COMMENT '修改时间',
  sys_dict_createuid VARCHAR(255) DEFAULT 'NULL' COMMENT '创建人',
  sys_dict_updateuid VARCHAR(255) DEFAULT 'NULL' COMMENT '更新人',
  PRIMARY KEY (sys_dict_id)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 3276
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '系统数据字典'
ROW_FORMAT = DYNAMIC;

--
-- Definition for table sys_file
--
DROP TABLE IF EXISTS sys_file;
CREATE TABLE sys_file (
  sys_file_id VARCHAR(255) NOT NULL COMMENT ' 主键',
  sys_file_name VARCHAR(50) DEFAULT 'NULL' COMMENT '文件名',
  sys_file_addr VARCHAR(255) DEFAULT 'NULL' COMMENT '文件地址',
  sys_file_updatedate DATETIME DEFAULT NULL COMMENT '更新时间',
  sys_file_createdate VARCHAR(255) DEFAULT 'NULL' COMMENT '创建时间',
  sys_file_updateuid VARCHAR(255) DEFAULT 'NULL' COMMENT '修改人',
  sys_file_createuid VARCHAR(255) DEFAULT 'NULL' COMMENT '创建人',
  PRIMARY KEY (sys_file_id)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 3276
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '系统文件'
ROW_FORMAT = DYNAMIC;

--
-- Definition for table sys_goods
--
DROP TABLE IF EXISTS sys_goods;
CREATE TABLE sys_goods (
  sys_goods_id VARCHAR(255) BINARY NOT NULL COMMENT '商品编号',
  sys_goods_name VARCHAR(255) BINARY DEFAULT 'NULL' COMMENT '商品名称',
  sys_goods_description VARCHAR(255) BINARY DEFAULT 'NULL' COMMENT '商品描述',
  sys_goods_price VARCHAR(255) BINARY DEFAULT 'NULL' COMMENT '起始价',
  sys_goods_imagepath VARCHAR(255) BINARY DEFAULT 'NULL' COMMENT '图片路径',
  sys_goods_amount VARCHAR(255) BINARY DEFAULT 'NULL' COMMENT '数量',
  sys_goods_stime DATETIME DEFAULT NULL COMMENT '开始时间',
  sys_goods_etime DATETIME DEFAULT NULL COMMENT '结束时间',
  sys_goods_type_d VARCHAR(255) BINARY DEFAULT 'NULL' COMMENT '产品类型:1_金融,2_国资',
  sys_goods_addr VARCHAR(255) BINARY DEFAULT 'NULL' COMMENT '商品地址',
  sys_user_id VARCHAR(255) BINARY DEFAULT 'NULL' COMMENT '拍卖者id',
  sys_goods_audit_d VARCHAR(255) BINARY DEFAULT '''2''' COMMENT '资产审核:1_通过,2_不通过',
  sys_goods_createdate DATETIME DEFAULT NULL COMMENT '创建时间',
  sys_goods_updatedate DATETIME DEFAULT NULL COMMENT '更新时间',
  sys_goods_createuid VARCHAR(255) BINARY DEFAULT 'NULL' COMMENT '创建人id',
  sys_goods_updateuid VARCHAR(255) BINARY DEFAULT 'NULL' COMMENT '修改人id',
  PRIMARY KEY (sys_goods_id)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_bin
COMMENT = '商品信息表'
ROW_FORMAT = DYNAMIC;

--
-- Definition for table sys_leave
--
DROP TABLE IF EXISTS sys_leave;
CREATE TABLE sys_leave (
  sys_leave_id VARCHAR(64) NOT NULL COMMENT '主键',
  sys_user_id VARCHAR(64) DEFAULT 'NULL' COMMENT '请假人主键',
  sys_leave_reason VARCHAR(255) DEFAULT 'NULL' COMMENT '请假原因',
  sys_leave_comment VARCHAR(255) DEFAULT 'NULL' COMMENT '请假备注',
  sys_leave_status VARCHAR(255) DEFAULT 'NULL' COMMENT '请假状态',
  sys_leave_time DATETIME DEFAULT NULL COMMENT '申请时间',
  sys_leave_begin_time DATETIME DEFAULT NULL COMMENT '请假开始时间',
  sys_leave_end_time DATETIME DEFAULT NULL COMMENT '请假结束时间',
  PRIMARY KEY (sys_leave_id)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '请假'
ROW_FORMAT = DYNAMIC;

--
-- Definition for table sys_menu
--
DROP TABLE IF EXISTS sys_menu;
CREATE TABLE sys_menu (
  sys_menu_id VARCHAR(32) NOT NULL COMMENT '主键',
  sys_menu_pid VARCHAR(32) DEFAULT 'NULL' COMMENT '父主键',
  sys_menu_name VARCHAR(50) DEFAULT 'NULL' COMMENT '菜单名称',
  sys_menu_url VARCHAR(500) DEFAULT 'NULL' COMMENT '菜单地址',
  sys_menu_order VARCHAR(2) DEFAULT null COMMENT '菜单排号',
  sys_menu_icon_url VARCHAR(50) DEFAULT 'NULL' COMMENT '菜单图标地址',
  PRIMARY KEY (sys_menu_id)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 780
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '系统菜单表'
ROW_FORMAT = DYNAMIC;

--
-- Definition for table sys_perm
--
DROP TABLE IF EXISTS sys_perm;
CREATE TABLE sys_perm (
  sys_perm_id VARCHAR(255) NOT NULL COMMENT '主键',
  sys_perm_pid VARCHAR(255) DEFAULT 'NULL' COMMENT '父主键',
  sys_perm_name VARCHAR(255) DEFAULT 'NULL' COMMENT '权限名称',
  sys_perm_flag VARCHAR(255) DEFAULT 'NULL' COMMENT '权限标识',
  sys_perm_url VARCHAR(255) DEFAULT 'NULL' COMMENT '权限地址',
  sys_perm_createdate DATETIME DEFAULT NULL COMMENT '创建时间',
  sys_perm_updatedate DATETIME DEFAULT NULL COMMENT '更新时间',
  sys_perm_createuid VARCHAR(255) DEFAULT 'NULL' COMMENT '创建人',
  sys_perm_updateuid VARCHAR(255) DEFAULT 'NULL' COMMENT '更新人',
  PRIMARY KEY (sys_perm_id)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 5461
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '系统权限表'
ROW_FORMAT = DYNAMIC;

--
-- Definition for table sys_procdef
--
DROP TABLE IF EXISTS sys_procdef;
CREATE TABLE sys_procdef (
  sys_procdef_id VARCHAR(64) BINARY NOT NULL,
  id VARCHAR(64) BINARY NOT NULL COMMENT '主键',
  version INT(11) DEFAULT NULL COMMENT '版本',
  category VARCHAR(255) BINARY DEFAULT 'NULL',
  name VARCHAR(255) BINARY DEFAULT 'NULL' COMMENT '流程定义名称',
  deployment_id VARCHAR(64) BINARY DEFAULT 'NULL' COMMENT '流程部署ID',
  resource_name VARCHAR(4000) BINARY DEFAULT 'NULL' COMMENT '源文件名称',
  diagram_resource_name VARCHAR(4000) BINARY DEFAULT 'NULL' COMMENT '源文件图片名称',
  description VARCHAR(4000) BINARY DEFAULT 'NULL',
  has_start_form_key TINYINT(4) DEFAULT NULL,
  has_graphical_notation TINYINT(4) DEFAULT NULL,
  suspension_state INT(11) DEFAULT NULL,
  tenant_id VARCHAR(255) BINARY DEFAULT '''''',
  PRIMARY KEY (sys_procdef_id),
  UNIQUE INDEX ACT_UNIQ_PROCDEF (tenant_id)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_bin
ROW_FORMAT = DYNAMIC;

--
-- Definition for table sys_res
--
DROP TABLE IF EXISTS sys_res;
CREATE TABLE sys_res (
  sys_res_id VARCHAR(255) NOT NULL COMMENT '主键',
  sys_res_pid VARCHAR(255) DEFAULT 'NULL' COMMENT '父主键',
  sys_res_name VARCHAR(255) DEFAULT 'NULL' COMMENT '资源名称',
  sys_res_order VARCHAR(255) DEFAULT 'NULL' COMMENT '资源排号',
  sys_res_flag VARCHAR(255) DEFAULT 'NULL' COMMENT '资源标识',
  sys_res_updatetime DATETIME DEFAULT NULL COMMENT '资源创建时间',
  sys_res_createtime DATETIME DEFAULT NULL COMMENT '资源更新时间',
  sys_res_updateuid VARCHAR(255) DEFAULT 'NULL' COMMENT '创建人',
  sys_res_createuid VARCHAR(255) DEFAULT 'NULL' COMMENT '更新人',
  PRIMARY KEY (sys_res_id)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 780
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '系统资源表'
ROW_FORMAT = DYNAMIC;

--
-- Definition for table sys_role
--
DROP TABLE IF EXISTS sys_role;
CREATE TABLE sys_role (
  sys_role_id VARCHAR(255) NOT NULL COMMENT '主键',
  sys_role_pid VARCHAR(255) DEFAULT 'NULL' COMMENT '父主键',
  sys_role_name VARCHAR(255) DEFAULT 'NULL' COMMENT '角色名称',
  sys_role_flag VARCHAR(255) DEFAULT 'NULL' COMMENT '角色标识',
  sys_role_createdate DATETIME DEFAULT NULL COMMENT '创建时间',
  sys_role_updatedate DATETIME DEFAULT NULL COMMENT '更新时间',
  sys_role_createuid VARCHAR(255) DEFAULT 'NULL' COMMENT '创建人',
  sys_role_updateuid VARCHAR(255) DEFAULT 'NULL' COMMENT '更新人',
  sys_role_test_d VARCHAR(255) DEFAULT 'NULL' COMMENT '测试:0_test0,1_test1',
  PRIMARY KEY (sys_role_id)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 4096
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '系统角色表'
ROW_FORMAT = DYNAMIC;

--
-- Definition for table sys_role_activiti
--
DROP TABLE IF EXISTS sys_role_activiti;
CREATE TABLE sys_role_activiti (
  sys_role_activiti_id VARCHAR(255) NOT NULL DEFAULT '''''' COMMENT '主键',
  sys_role_id VARCHAR(255) DEFAULT 'NULL' COMMENT '角色主键',
  sys_activiti_id VARCHAR(255) DEFAULT 'NULL' COMMENT '流程id',
  sys_role_activiti_type VARCHAR(255) DEFAULT 'NULL' COMMENT 'partsel有子节点被选中selected选中的节点',
  PRIMARY KEY (sys_role_activiti_id)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 2730
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '角色流程表'
ROW_FORMAT = DYNAMIC;

--
-- Definition for table sys_role_menu
--
DROP TABLE IF EXISTS sys_role_menu;
CREATE TABLE sys_role_menu (
  sys_role_menu_id VARCHAR(255) NOT NULL COMMENT '主键',
  sys_role_id VARCHAR(255) DEFAULT 'NULL' COMMENT '角色主键',
  sys_menu_id VARCHAR(255) DEFAULT 'NULL' COMMENT '菜单主键',
  sys_role_menu_type VARCHAR(255) DEFAULT 'NULL' COMMENT 'partsel有子节点被选中selected选中的节点',
  sys_role_menu_createdate DATETIME DEFAULT NULL COMMENT '创建时间',
  sys_role_menu_updatedate DATETIME DEFAULT NULL COMMENT '更新时间',
  sys_role_menu_createuid VARCHAR(255) DEFAULT 'NULL' COMMENT '创建人',
  sys_role_menu_updateuid VARCHAR(255) DEFAULT 'NULL' COMMENT '更新人',
  PRIMARY KEY (sys_role_menu_id)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 8192
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '角色菜单表'
ROW_FORMAT = DYNAMIC;

--
-- Definition for table sys_role_perm
--
DROP TABLE IF EXISTS sys_role_perm;
CREATE TABLE sys_role_perm (
  sys_role_perm_id VARCHAR(255) NOT NULL COMMENT '主键',
  sys_role_id VARCHAR(255) DEFAULT 'NULL' COMMENT '角色主键',
  sys_perm_id VARCHAR(255) DEFAULT 'NULL' COMMENT '权限主键',
  sys_role_perm_type VARCHAR(255) DEFAULT 'NULL' COMMENT 'partsel有子节点被选中,本身是未选中状态;selected选中的节点',
  sys_role_perm_createdate DATETIME DEFAULT NULL COMMENT '创建时间',
  sys_role_perm_updatedate DATETIME DEFAULT NULL COMMENT '更新时间',
  sys_role_perm_createuid VARCHAR(255) DEFAULT 'NULL' COMMENT '创建人',
  sys_role_perm_updateuid VARCHAR(255) DEFAULT 'NULL' COMMENT '更新人',
  PRIMARY KEY (sys_role_perm_id)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 3276
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '角色权限表'
ROW_FORMAT = DYNAMIC;

--
-- Definition for table sys_role_res
--
DROP TABLE IF EXISTS sys_role_res;
CREATE TABLE sys_role_res (
  sys_role_res_id VARCHAR(255) NOT NULL COMMENT '主键',
  sys_role_id VARCHAR(255) DEFAULT 'NULL' COMMENT '角色主键',
  sys_res_id VARCHAR(255) DEFAULT 'NULL' COMMENT '资源主键',
  sys_role_res_type VARCHAR(255) DEFAULT 'NULL' COMMENT 'partsel有子节点被选中,selected选中的节点',
  sys_role_res_createtime DATETIME DEFAULT NULL COMMENT '创建时间',
  sys_role_res_updatetime DATETIME DEFAULT NULL COMMENT '更新时间',
  sys_role_res_createuid VARCHAR(255) DEFAULT 'NULL' COMMENT '创建人',
  sys_role_res_updateuid VARCHAR(255) DEFAULT 'NULL' COMMENT '更新人',
  PRIMARY KEY (sys_role_res_id)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 8192
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '角色资源表'
ROW_FORMAT = DYNAMIC;

--
-- Definition for table sys_user
--
DROP TABLE IF EXISTS sys_user;
CREATE TABLE sys_user (
  sys_user_id VARCHAR(255) NOT NULL COMMENT '主键',
  sys_user_name VARCHAR(255) DEFAULT 'NULL' COMMENT '姓名',
  sys_user_account VARCHAR(255) DEFAULT 'NULL' COMMENT '帐号',
  sys_user_password VARCHAR(255) DEFAULT 'NULL' COMMENT '密码',
  sys_user_login_date DATETIME DEFAULT NULL COMMENT '最后登陆时间',
  sys_user_login_ip VARCHAR(255) DEFAULT 'NULL' COMMENT '登陆ip地址',
  sys_user_status_d VARCHAR(255) DEFAULT 'NULL' COMMENT '用户状态:0_有效用户,1_无效用户',
  sys_user_card VARCHAR(255) DEFAULT 'NULL' COMMENT '身份证号',
  sys_user_flag_c VARCHAR(255) DEFAULT 'NULL' COMMENT '用户标记:0_系统用户,1_注册用户,2_双身份',
  sys_user_reg_date DATETIME DEFAULT NULL COMMENT '注册时间',
  sys_user_reg_type_d VARCHAR(255) DEFAULT 'NULL' COMMENT '用户来源:0_pc端,1_iso端,2_android端',
  sys_area_id VARCHAR(255) DEFAULT 'NULL' COMMENT '所在地主键',
  sys_org_id VARCHAR(255) DEFAULT 'NULL' COMMENT '组织机构主键',
  sys_user_createdate DATETIME DEFAULT NULL COMMENT '创建时间',
  sys_user_updatedate DATETIME DEFAULT NULL COMMENT '更新时间',
  sys_user_createuid VARCHAR(255) DEFAULT 'NULL' COMMENT '创建人id',
  sys_user_updateuid VARCHAR(255) DEFAULT 'NULL' COMMENT '修改人id',
  PRIMARY KEY (sys_user_id)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 1489
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '系统用户表'
ROW_FORMAT = DYNAMIC;

--
-- Definition for table sys_user_role
--
DROP TABLE IF EXISTS sys_user_role;
CREATE TABLE sys_user_role (
  sys_user_role_id VARCHAR(255) NOT NULL COMMENT '主键',
  sys_user_id VARCHAR(255) DEFAULT 'NULL' COMMENT '用户主键',
  sys_role_id VARCHAR(255) DEFAULT 'NULL' COMMENT '角色主键',
  sys_user_role_type VARCHAR(255) DEFAULT 'NULL' COMMENT 'partsel有子节点被选中selected选中的节点',
  sys_user_role_createdate DATETIME DEFAULT NULL COMMENT '创建时间',
  sys_user_role_updatedate DATETIME DEFAULT NULL COMMENT '更新时间',
  sys_user_role_createuid VARCHAR(255) DEFAULT 'NULL' COMMENT '创建人',
  sys_user_role_updateuid VARCHAR(255) DEFAULT 'NULL' COMMENT '更新人',
  PRIMARY KEY (sys_user_role_id)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 8192
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '用户角色表'
ROW_FORMAT = DYNAMIC;

--
-- Definition for table act_ge_bytearray
--
DROP TABLE IF EXISTS act_ge_bytearray;
CREATE TABLE act_ge_bytearray (
  ID_ VARCHAR(64) BINARY NOT NULL,
  REV_ INT(11) DEFAULT NULL,
  NAME_ VARCHAR(255) BINARY DEFAULT 'NULL',
  DEPLOYMENT_ID_ VARCHAR(64) BINARY DEFAULT 'NULL',
  BYTES_ LONGBLOB DEFAULT NULL,
  GENERATED_ TINYINT(4) DEFAULT NULL,
  PRIMARY KEY (ID_),
  CONSTRAINT ACT_FK_BYTEARR_DEPL FOREIGN KEY (DEPLOYMENT_ID_)
    REFERENCES act_re_deployment(ID_) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_bin
ROW_FORMAT = DYNAMIC;

--
-- Definition for table act_id_membership
--
DROP TABLE IF EXISTS act_id_membership;
CREATE TABLE act_id_membership (
  USER_ID_ VARCHAR(64) BINARY NOT NULL,
  GROUP_ID_ VARCHAR(64) BINARY NOT NULL,
  PRIMARY KEY (USER_ID_, GROUP_ID_),
  CONSTRAINT ACT_FK_MEMB_GROUP FOREIGN KEY (GROUP_ID_)
    REFERENCES act_id_group(ID_) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT ACT_FK_MEMB_USER FOREIGN KEY (USER_ID_)
    REFERENCES act_id_user(ID_) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_bin
ROW_FORMAT = DYNAMIC;


--
INSERT INTO sys_activiti VALUES
('25ec957398e64e138c968804f3c45246', 'root', '请假流程', 'SysLeave', 'SysLeave'),
('2ec0bc9be8d442c999054024e0954f39', '25ec957398e64e138c968804f3c45246', '经济人审批', 'SysLeave_usertask2', '经济人审批'),
('a1a5bae83b734816ae223ef75bb32848', '25ec957398e64e138c968804f3c45246', '提交申请', 'SysLeave_usertask1', '提交申请'),
('da776ffe989a44f5b0a3af9d5983d0aa', '25ec957398e64e138c968804f3c45246', '老总审批', 'SysLeave_usertask3', '老总审批');

-- 
-- Dumping data for table sys_area
--

-- Table adminltemy.sys_area does not contain any data (it is empty)

-- 
-- Dumping data for table sys_buy
--

-- Table adminltemy.sys_buy does not contain any data (it is empty)

-- 
-- Dumping data for table sys_deploy
--

-- Table adminltemy.sys_deploy does not contain any data (it is empty)

-- 
-- Dumping data for table sys_dict
--
INSERT INTO sys_dict VALUES
('04dba99e3d784e878b5e7a2ec2262a96', '6243f1eafd9a4d2093e8a3265714efab', '用户状态', 'sys_user_status_d', 0, '0', '2017-04-21 18:39:14', '2017-04-21 18:39:14', NULL, NULL),
('0b34577203734a9b94ea5dade26879ca', '04dba99e3d784e878b5e7a2ec2262a96', '审核通过', '1', 0, '0', '2017-04-21 18:39:14', '2017-08-14 03:42:49', NULL, NULL),
('1541c21c54954230b3a04ec4fc22c656', 'a09bb601ea5e445e88b883b1d5c03680', '金融', '1', 0, '0', '2017-09-09 00:59:31', '2017-09-09 00:59:31', NULL, NULL),
('29e1ec45542b4082af0aa16a1142a9c1', '431cf88631ca47dda0e1ddd4d514f5af', '用户标记', 'flag_c', 0, '0', '2017-04-21 03:10:23', '2017-04-21 03:10:23', NULL, NULL),
('318c95adf813498a8fa6c5066ef4ea54', '6c7e136007c54ddc83a567e10f370b36', '通过', '1', 0, '0', '2017-09-09 00:59:31', '2017-09-09 00:59:31', NULL, NULL),
('37b73a43f23a42edb6bef45a96628217', 'c3867713ee74484da5e13675002ed2f2', '普通用户', '1', 0, '0', '2017-04-21 18:39:14', '2017-08-14 03:41:47', NULL, NULL),
('3bc4cc6596a04fe0a2cc1fa2ccd485bf', 'root', 'sys_buy', 'sys_buy', 0, '0', '2017-08-21 01:45:44', '2017-08-21 01:45:44', NULL, NULL),
('3c1c9c7485d846d8aac093eb443549aa', 'c562eaea0c374397b54db80381712a3e', '男', '1', NULL, NULL, NULL, NULL, NULL, NULL),
('431cf88631ca47dda0e1ddd4d514f5af', 'root', '共用', 'common', NULL, NULL, NULL, NULL, NULL, NULL),
('5659c944954540cebaf099843acf5d1a', 'd809b08967234ea18b9c5dd233efccb8', '成功', '1', 0, '0', '2017-08-21 01:45:44', '2017-08-21 01:45:44', NULL, NULL),
('57f2343bb1714badbd379200de170abd', 'c562eaea0c374397b54db80381712a3e', '女', '2', NULL, NULL, NULL, NULL, NULL, NULL),
('6243f1eafd9a4d2093e8a3265714efab', 'root', 'sys_user', 'sys_user', 0, '0', '2017-04-21 18:39:14', '2017-04-21 18:39:14', NULL, NULL),
('6c7e136007c54ddc83a567e10f370b36', '915e0c030de04bf08e5bc6761a7c8c2d', '资产审核', 'sys_goods_audit_d', 0, '0', '2017-09-09 00:59:31', '2017-09-09 00:59:31', NULL, NULL),
('880d185f11794395a9439705eab558e0', '04dba99e3d784e878b5e7a2ec2262a96', '待审核', '0', 0, '0', '2017-04-21 18:39:14', '2017-08-14 03:43:01', NULL, NULL),
('8901dac3d4f047259869010aa8e4c1bc', '29e1ec45542b4082af0aa16a1142a9c1', '注册用户', '1', 0, '0', '2017-04-21 03:10:23', '2017-04-21 03:10:23', NULL, NULL),
('915e0c030de04bf08e5bc6761a7c8c2d', 'root', 'sys_goods', 'sys_goods', 0, '0', '2017-09-09 00:59:31', '2017-09-09 00:59:31', NULL, NULL),
('a09bb601ea5e445e88b883b1d5c03680', '915e0c030de04bf08e5bc6761a7c8c2d', '产品类型', 'sys_goods_type_d', 0, '0', '2017-09-09 00:59:31', '2017-09-09 00:59:31', NULL, NULL),
('a21d1190c70545c6a8fe63916c72b0d4', 'root', 'sys_role', 'sys_role', 0, '0', '2017-04-21 18:53:35', '2017-04-21 18:53:35', NULL, NULL),
('a52bc1e447e640a9a7a8ece5b675eab0', '6c7e136007c54ddc83a567e10f370b36', '不通过', '2', 0, '0', '2017-09-09 00:59:31', '2017-09-09 00:59:31', NULL, NULL),
('a55c6e261e774082bbd5521130c5c1e6', 'c3867713ee74484da5e13675002ed2f2', '加盟方', '2', 0, '0', '2017-04-21 18:39:14', '2017-08-14 03:41:55', NULL, NULL),
('a6a5b5dffe754fd5901698bf10cf2f15', '29e1ec45542b4082af0aa16a1142a9c1', '双身份', '2', 0, '0', '2017-04-21 03:10:23', '2017-04-21 03:10:23', NULL, NULL),
('a77fda4f171f45f1b089f0dd18221e22', 'c3867713ee74484da5e13675002ed2f2', '企业发布方', '0', 0, '0', '2017-04-21 18:39:14', '2017-08-14 03:42:23', NULL, NULL),
('ac2995fcb30942a1a3a459b03f030649', '29e1ec45542b4082af0aa16a1142a9c1', '系统用户', '0', 0, '0', '2017-04-21 03:10:23', '2017-04-21 03:10:23', NULL, NULL),
('c3867713ee74484da5e13675002ed2f2', '6243f1eafd9a4d2093e8a3265714efab', '用户来源', 'sys_user_reg_type_d', 0, '0', '2017-04-21 18:39:14', '2017-04-21 18:39:14', NULL, NULL),
('c562eaea0c374397b54db80381712a3e', '431cf88631ca47dda0e1ddd4d514f5af', '性别', 'sex_c', NULL, NULL, NULL, NULL, NULL, NULL),
('cc9770cee62c4b8fa4fd4539e2e8a1fb', 'a21d1190c70545c6a8fe63916c72b0d4', '测试', 'sys_role_test_d', 0, '0', '2017-04-21 18:53:35', '2017-04-21 18:53:35', NULL, NULL),
('d809b08967234ea18b9c5dd233efccb8', '3bc4cc6596a04fe0a2cc1fa2ccd485bf', '成功状态', 'sys_buy_succ_d', 0, '0', '2017-08-21 01:45:44', '2017-08-21 01:45:44', NULL, NULL),
('d8f8be8e778a477c93ae2fd272f7932b', 'a09bb601ea5e445e88b883b1d5c03680', '国资', '2', 0, '0', '2017-09-09 00:59:31', '2017-09-09 00:59:31', NULL, NULL),
('e481ad7d632b48b1b964263c3238038a', 'cc9770cee62c4b8fa4fd4539e2e8a1fb', 'test0', '0', 0, '0', '2017-04-21 18:53:35', '2017-04-21 18:53:35', NULL, NULL),
('f93f88d8c8c94d9a9ec4b79300b074ba', 'cc9770cee62c4b8fa4fd4539e2e8a1fb', 'test1', '1', 0, '0', '2017-04-21 18:53:35', '2017-04-21 18:53:35', NULL, NULL),
('fdede2f6d5d34dcc9ab6a13345ef206c', 'd809b08967234ea18b9c5dd233efccb8', '不成功', '0', 0, '0', '2017-08-21 01:45:44', '2017-08-21 01:45:44', NULL, NULL);

-- 
-- Dumping data for table sys_file
--
INSERT INTO sys_file VALUES
('70d7ec363ef044ed8ff814566ab974c4', '招聘帐号.txt', 'E:/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/adminltemy/sysfile/招聘帐号.txt', '2017-05-02 10:27:46', '2017-05-02 10:27:46', 'da8c252c6672450db9a4af267aa5e6ad', 'da8c252c6672450db9a4af267aa5e6ad');

-- 
-- Dumping data for table sys_goods
--
INSERT INTO sys_goods VALUES
('4abc8eb9a11a4b269a87d6318915f0a7', '1', 'e', 'e', 'e', 'e', '2017-09-04 00:00:00', '2017-09-05 00:00:00', NULL, NULL, NULL, '2', '2017-09-09 01:15:54', '2017-09-09 01:16:05', 'da8c252c6672450db9a4af267aa5e6ad', 'da8c252c6672450db9a4af267aa5e6ad');

-- 
-- Dumping data for table sys_leave
--
INSERT INTO sys_leave VALUES
('a546e140a7354e8c9e0d5b8df53d42c2', 'da8c252c6672450db9a4af267aa5e6ad', '1', '1', '1', '2016-10-11 00:00:00', '2016-10-11 00:00:00', '2016-10-06 00:00:00'),
('b647917b19764e89ac04305c56df6dcd', 'a3e6fea5c0cb4efabf1cfd9f0c93fe28', '1', '1', '1', '2016-10-04 00:00:00', '2016-10-04 00:00:00', '2016-10-12 00:00:00');

-- 
-- Dumping data for table sys_menu
--
INSERT INTO sys_menu VALUES
('0ccd416d257246d79231d7db876a9075', 'root', '系统管理', '', '', ''),
('19d9e0d3ecff4e339de7d910b6227c67', '0ccd416d257246d79231d7db876a9075', '角色配置', 'sys/role/treerolemenupermconf', '', ''),
('26dc8309b2f8414b924b6166d821a637', 'e72d1f637ac940aebbe2a36e0b2e0a88', '资产查询', 'sys/goods/list', NULL, NULL),
('31a453c233c8447fa39759b8abefc905', '', '', '', '', ''),
('41ab04a45d1847a4aa50235f57a87de1', '0ccd416d257246d79231d7db876a9075', '用户管理', 'sys/user/list', '', ''),
('4956bfb16ac14cb4856abe4a4ebc449d', 'fdf99edaa39148b7a894881a0a5d1c6f', '请假办理', 'sys/task/list?processKey=SysLeave', '', ''),
('4b9c7c37534b481684755e02aaa40fd7', '', '', '', '', ''),
('512faabc2b0141adacbef614220cf7e0', '0ccd416d257246d79231d7db876a9075', '数据字典', 'sys/dict/tree', NULL, NULL),
('53a3fbe9d0384791b1f9d243487a4922', '', '', '', '', ''),
('6e4e2a5ccee04c85a991b75a7c14f8dd', '', '', '', '', ''),
('7cf4df6cb8664d2db99f4bbab5aea44b', '9e5fb647769b4162b6ba80ad19433741', '角色配置', 'sys/role/treeroleactiviticonf', '', ''),
('817e76595b5241d386c4a66f0122d599', 'root', '用户管理', NULL, NULL, NULL),
('9e5fb647769b4162b6ba80ad19433741', 'root', '流程管理', '', '', ''),
('b409189f42654fd6a06a7a068113d565', '0ccd416d257246d79231d7db876a9075', '系统文件管理', 'sys/file/list', NULL, NULL),
('b5a632a7a466441294ca53f93571623c', 'd89d4708bdd7406da6f684e4a8d21f2a', '购买记录', 'sys/buy/list', NULL, NULL),
('b5ec76178e1b4553947e879dae19461f', '', '', '', '', ''),
('ca0481f406074859a9de0cfafe092221', '0ccd416d257246d79231d7db876a9075', '权限管理', 'sys/perm/tree', '', ''),
('ce4a476e9b54400aa1e4da83e6055331', '9e5fb647769b4162b6ba80ad19433741', '流程部署', 'sys/deploy/list', '', ''),
('d005b1898de74061b5fbde648e54dfec', '9e5fb647769b4162b6ba80ad19433741', '节点管理', 'sys/activiti/tree', '', ''),
('d34613d0db6142bda9a675eb7fc9d8e5', '9e5fb647769b4162b6ba80ad19433741', '流程定义', 'sys/procdef/list', '', ''),
('d482851118be4674b09fb386a7bdd02c', '', '', '', '', ''),
('d48e75286b38452897e6e861a9922b1f', '817e76595b5241d386c4a66f0122d599', '加盟商审核', 'sys/user/query?sys_user_reg_type_d=a55c6e261e774082bbd5521130c5c1e6', NULL, NULL),
('d48e75286b38452897e6e861a9924b1f', '817e76595b5241d386c4a66f0122d599', '用户审核', 'sys/user/query?sys_user_reg_type_d=37b73a43f23a42edb6bef45a96628217', NULL, NULL),
('d48e75286b38452897e6e861a9924b9f', '817e76595b5241d386c4a66f0122d599', '用户查询', 'sys/user/query', NULL, NULL),
('d89d4708bdd7406da6f684e4a8d21f2a', 'root', '购买管理', NULL, NULL, NULL),
('e3e5d57933b84d4b80c7b6dd9860c9d4', '0ccd416d257246d79231d7db876a9075', '角色管理', 'sys/role/tree', '', ''),
('e72d1f637ac940aebbe2a36e0b2e0a88', 'root', '资产管理', NULL, NULL, NULL),
('e7dc8a885290493fa3283b196d9ee787', '0ccd416d257246d79231d7db876a9075', '菜单管理', 'sys/menu/tree', '', ''),
('f6f3b0334aa646a88f92d059fc9e5ca8', '', '', '', '', ''),
('f7cd6582eb4b47b6b623cd5f29ff751e', 'fdf99edaa39148b7a894881a0a5d1c6f', '请假管理', 'sys/leave/list', '', ''),
('fdf99edaa39148b7a894881a0a5d1c6f', 'root', '业务管理', '', '', '');

-- 
-- Dumping data for table sys_perm
--
INSERT INTO sys_perm VALUES
('01af93d9fb2c4e77a3cfab9888cced5b', '1e77eaad20c74e1c9898dede322a9a12', '删除树节点', 'perms[sysRole:deltree]', '/sys/role/deltree', '2017-04-19 09:46:32', '2017-04-19 09:46:32', NULL, NULL),
('03cab5e4e7f5414a9ff91b65485e4468', '1e77eaad20c74e1c9898dede322a9a12', '批量删除', 'perms[sysRole:delall]', '/sys/role/delall', '2017-04-19 09:46:31', '2017-04-19 09:46:31', NULL, NULL),
('046548c1df5e4b868b0961fcae0bef18', '1e77eaad20c74e1c9898dede322a9a12', '保存页面', 'perms[sysRole:goadd]', '/sys/role/goadd', '2017-04-19 09:46:31', '2017-04-19 09:46:31', NULL, NULL),
('061ac5000c5547878fe946094c5342a3', '2e3ef8186ff44080897aaa07cbd48adf', '删除', 'perms[sysBuy:del]', '/sys/buy/del', '2017-08-21 01:46:30', '2017-08-21 01:46:30', NULL, NULL),
('07dbe4e39db548df9e53aa1e4e50e737', '14a4ed27e5fb433599a50157b66be691', '树页面', 'perms[sysGoods:tree]', '/sys/buy/tree', '2017-09-09 00:58:27', '2017-09-09 00:58:27', NULL, NULL),
('0d736d08c24e40b6b7a8022197318057', '2dcdf7724f8f4d8eaf3c9fce6a0d8e3d', '增加页面', 'perms[sysFile:goadd]', '/sys/file/goadd', '2017-05-02 10:27:12', '2017-05-02 10:27:12', NULL, NULL),
('0eae92d5888548b699f3d05a47b6ab1c', '2e3ef8186ff44080897aaa07cbd48adf', '修改页面', 'perms[sysBuy:goedit]', '/sys/buy/goedit', '2017-08-21 01:46:30', '2017-08-21 01:46:30', NULL, NULL),
('113bcf7431f4470c8e7535afc0aff581', '2e3ef8186ff44080897aaa07cbd48adf', '页面', 'perms[sysBuy:pages]', '/pages/sys/buy/**', '2017-08-21 01:46:30', '2017-08-21 01:46:30', NULL, NULL),
('1218e874069144a687aab44cebc234eb', '4dcca247b7134c3ab3156e2dea30860f', '保存', 'perms[sysPerm:save]', '/sys/perm/save', '2017-04-19 09:17:14', '2017-04-19 09:17:14', NULL, NULL),
('12c69d4925c34d399be31fce3037be9a', '14a4ed27e5fb433599a50157b66be691', '删除树节点', 'perms[sysGoods:deltree]', '/sys/buy/deltree', '2017-09-09 00:58:27', '2017-09-09 00:58:27', NULL, NULL),
('14a4ed27e5fb433599a50157b66be691', 'root', '用户管理', 'perms[sysGoods:all]', '/sys/buy/**', '2017-09-09 00:58:27', '2017-09-09 00:58:27', NULL, NULL),
('1528901f1409476ea0b2d3498b9c013a', '6b53d41674374feb9c9fe122c386e62b', '树页面', 'perms[sysDict:tree]', '/sys/dict/tree', '2017-04-20 17:38:03', '2017-04-20 17:38:03', NULL, NULL),
('18226bf4b23d427c9362f6e893407714', 'eeceec9f880d4f7eaa7d255655a1a25a', '修改页面', 'perms[sysMenu:goedit]', '/sys/menu/goedit', '2017-04-18 17:10:27', '2017-04-18 17:10:27', NULL, NULL),
('1ae99746820d4c2882e5cd472d9b52f7', '6b53d41674374feb9c9fe122c386e62b', '页面', 'perms[sysDict:pages]', '/pages/sys/dict/**', '2017-04-20 17:38:03', '2017-04-20 17:38:03', NULL, NULL),
('1c8165c0f4d146acbc381cd1395a5d9f', '4dcca247b7134c3ab3156e2dea30860f', '树页面', 'perms[sysPerm:tree]', '/sys/perm/tree', '2017-04-19 09:17:14', '2017-04-19 09:17:14', NULL, NULL),
('1e77eaad20c74e1c9898dede322a9a12', 'root', '角色管理', 'perms[sysRole:all]', '/sys/role/**', '2017-04-19 09:46:31', '2017-04-19 09:46:31', NULL, NULL),
('1f98b20cca794e92a3a349409518ad25', 'root', '用户管理', 'perms[sysDict:all]', '/sys/file/**', '2017-05-02 10:24:20', '2017-05-02 10:24:20', NULL, NULL),
('217c32ca9b974fafa2c8963e4d7d302b', '1e77eaad20c74e1c9898dede322a9a12', '保存树', 'perms[sysRole:savetree]', '/sys/role/savetree', '2017-04-19 09:46:32', '2017-04-19 09:46:32', NULL, NULL),
('2187824e583d49ffbc80c19b55eba26a', '1e77eaad20c74e1c9898dede322a9a12', '树页面', 'perms[sysRole:tree]', '/sys/role/tree', '2017-04-19 09:46:32', '2017-04-19 09:46:32', NULL, NULL),
('2700adcfcece44fea01c7770feac2b81', '4f4ed019e53b4cd3a5f1c74531197a41', '修改页面', 'perms[sysUser:goedit]', '/sys/user/goedit', '2017-04-18 15:20:55', '2017-04-18 15:20:55', NULL, NULL),
('270663f30c8f4b41aeb41b169ff3b783', '2dcdf7724f8f4d8eaf3c9fce6a0d8e3d', '上传', 'perms[sysFile:upload]', '/sys/file/upload', '2017-05-02 10:27:12', '2017-05-02 10:27:12', NULL, NULL),
('288357c2378a4c6082f01d7aeaa4eaac', '4f4ed019e53b4cd3a5f1c74531197a41', '增加', 'perms[sysUser:save]', '/sys/user/save', '2017-04-18 15:20:55', '2017-04-18 15:20:55', NULL, NULL),
('28ebbfdcc4e74a4d9c01e25d99b8b897', '1e77eaad20c74e1c9898dede322a9a12', '修改页面', 'perms[sysRole:goedit]', '/sys/role/goedit', '2017-04-19 09:46:31', '2017-04-19 09:46:31', NULL, NULL),
('2dcdf7724f8f4d8eaf3c9fce6a0d8e3d', 'root', '用户管理', 'perms[sysFile:all]', '/sys/file/**', '2017-05-02 10:27:12', '2017-05-02 10:27:12', NULL, NULL),
('2e3ef8186ff44080897aaa07cbd48adf', 'root', '购买管理', 'perms[sysBuy:all]', '/sys/buy/**', '2017-08-21 01:46:30', '2017-08-21 01:46:30', NULL, NULL),
('3399210f4cce4461b5c27c5dceb525b4', 'f153ad366c0c44ce8ab2b66d8a7575b8', '增加页面', 'perms[sysDict:goadd]', '/sys/file/goadd', '2017-05-02 09:59:34', '2017-05-02 09:59:34', NULL, NULL),
('38486d00b1d24e4caf7cb845af9c4824', '6b53d41674374feb9c9fe122c386e62b', '修改页面', 'perms[sysDict:goedit]', '/sys/dict/goedit', '2017-04-20 17:38:03', '2017-04-20 17:38:03', NULL, NULL),
('3950eb3e1352457f9d03767b15d5b08e', 'root', '请假办理', 'perms[sysTask:all]', '/sys/task/**', NULL, NULL, NULL, NULL),
('3a49e7a494ab40339d8623abddc226ad', '2e3ef8186ff44080897aaa07cbd48adf', '增加页面', 'perms[sysBuy:goadd]', '/sys/buy/goadd', '2017-08-21 01:46:30', '2017-08-21 01:46:30', NULL, NULL),
('3aa00316db7a48bb908621923d8e0bb7', 'eeceec9f880d4f7eaa7d255655a1a25a', '修改', 'perms[sysMenu:edit]', '/sys/menu/edit', '2017-04-18 17:10:27', '2017-04-18 17:10:27', NULL, NULL),
('3bb3f4e8af914b03a0289b835ce319db', '2dcdf7724f8f4d8eaf3c9fce6a0d8e3d', '修改页面', 'perms[sysFile:goedit]', '/sys/file/goedit', '2017-05-02 10:27:13', '2017-05-02 10:27:13', NULL, NULL),
('3e1440f0a35144e688d9d07c7464038a', '14a4ed27e5fb433599a50157b66be691', '保存页面', 'perms[sysGoods:goadd]', '/sys/buy/goadd', '2017-09-09 00:58:27', '2017-09-09 00:58:27', NULL, NULL),
('43a254960d7c484b8e104ae335eaa3b6', 'eeceec9f880d4f7eaa7d255655a1a25a', '查询树节点', 'perms[sysMenu:treenode]', '/sys/menu/treenode', '2017-04-18 17:10:27', '2017-04-18 17:10:27', NULL, NULL),
('43a5e346fb9b49ab8f482a3c9895ef37', 'root', '请假管理', 'perms[sysLeave:all]', '/sys/leave/**', NULL, NULL, NULL, NULL),
('447f1687559b47088aaf0eddcbba9ac2', 'f153ad366c0c44ce8ab2b66d8a7575b8', '列表', 'perms[sysDict:list]', '/sys/file/list', '2017-05-02 09:59:34', '2017-05-02 09:59:34', NULL, NULL),
('4a0ca82beafe41089452c742be284004', '4f4ed019e53b4cd3a5f1c74531197a41', '树列表', 'perms[sysUser:listtree]', '/sys/user/listtree', '2017-04-18 15:20:54', '2017-04-18 15:20:54', NULL, NULL),
('4ba7260f93c04271ac3fa4a01e08207d', '4dcca247b7134c3ab3156e2dea30860f', '查询所有树节点', 'perms[sysPerm:treenodeall]', '/sys/perm/treenodeall', '2017-04-19 09:17:14', '2017-04-19 09:17:14', NULL, NULL),
('4c53bf8b728c4c69b4ee06429b655384', '4f4ed019e53b4cd3a5f1c74531197a41', '上传', 'perms[sysUser:upload]', '/sys/user/upload', '2017-04-18 15:20:55', '2017-04-18 15:20:55', NULL, NULL),
('4dcca247b7134c3ab3156e2dea30860f', 'root', '权限管理', 'perms[sysPerm:all]', '/sys/perm/**', '2017-04-19 09:17:14', '2017-04-19 09:17:14', NULL, NULL),
('4f4ed019e53b4cd3a5f1c74531197a41', 'root', '用户管理', 'perms[sysUser:all]', '/sys/user/**', '2017-04-18 15:20:54', '2017-04-18 15:20:54', NULL, NULL),
('58b17be87b7c44f3851b9552f923f1e0', '4dcca247b7134c3ab3156e2dea30860f', '删除', 'perms[sysPerm:del]', '/sys/perm/del', '2017-04-19 09:17:14', '2017-04-19 09:17:14', NULL, NULL),
('5b62d85911164dff805caafc67a86b46', '14a4ed27e5fb433599a50157b66be691', '页面', 'perms[sysGoods:pages]', '/pages/sys/buy/**', '2017-09-09 00:58:27', '2017-09-09 00:58:27', NULL, NULL),
('5df72d7a06914cd2a379bbe94d0d1647', '2e3ef8186ff44080897aaa07cbd48adf', '上传', 'perms[sysBuy:upload]', '/sys/buy/upload', '2017-08-21 01:46:30', '2017-08-21 01:46:30', NULL, NULL),
('674467a60c0648afaf8d8fe1c1c49a3d', '4dcca247b7134c3ab3156e2dea30860f', '修改页面', 'perms[sysPerm:goedit]', '/sys/perm/goedit', '2017-04-19 09:17:14', '2017-04-19 09:17:14', NULL, NULL),
('67b2a0a8603b4211ab80ae1ca4985993', '14a4ed27e5fb433599a50157b66be691', '保存', 'perms[sysGoods:save]', '/sys/buy/save', '2017-09-09 00:58:27', '2017-09-09 00:58:27', NULL, NULL),
('68458da2f2da4de88b8973f5fc228a73', 'eeceec9f880d4f7eaa7d255655a1a25a', '页面', 'perms[sysMenu:pages]', '/pages/sys/menu/**', '2017-04-18 17:10:26', '2017-04-18 17:10:26', NULL, NULL),
('69ad388c742b4ae6ae1ff3998401b1e5', '1e77eaad20c74e1c9898dede322a9a12', '修改', 'perms[sysRole:edit]', '/sys/role/edit', '2017-04-19 09:46:31', '2017-04-19 09:46:31', NULL, NULL),
('6abd65e456414c53acd905023b3eaf8e', '4f4ed019e53b4cd3a5f1c74531197a41', '删除', 'perms[sysUser:del]', '/sys/user/del', '2017-04-18 15:20:55', '2017-04-18 15:20:55', NULL, NULL),
('6b36f930884041fc90922941d582a900', '2dcdf7724f8f4d8eaf3c9fce6a0d8e3d', '页面', 'perms[sysFile:pages]', '/pages/sys/file/**', '2017-05-02 10:27:12', '2017-05-02 10:27:12', NULL, NULL),
('6b53d41674374feb9c9fe122c386e62b', 'root', '字典管理', 'perms[sysDict:all]', '/sys/dict/**', '2017-04-20 17:38:03', '2017-04-20 17:38:03', NULL, NULL),
('77ae10cf02314b809325648c49cac4fc', '2e3ef8186ff44080897aaa07cbd48adf', '增加', 'perms[sysBuy:save]', '/sys/buy/save', '2017-08-21 01:46:30', '2017-08-21 01:46:30', NULL, NULL),
('780df5bf5b26488e856856b0c3b874ba', '1e77eaad20c74e1c9898dede322a9a12', '查询树节点', 'perms[sysRole:treenode]', '/sys/role/treenode', '2017-04-19 09:46:32', '2017-04-19 09:46:32', NULL, NULL),
('79fab9d83792482d82f173014f37eb29', '14a4ed27e5fb433599a50157b66be691', '查询树节点', 'perms[sysGoods:treenode]', '/sys/buy/treenode', '2017-09-09 00:58:27', '2017-09-09 00:58:27', NULL, NULL),
('7b310ca13c224883b5501e062fd2533e', 'f153ad366c0c44ce8ab2b66d8a7575b8', '增加', 'perms[sysDict:save]', '/sys/file/save', '2017-05-02 09:59:34', '2017-05-02 09:59:34', NULL, NULL),
('8221aa26b4cf4f0a8d933a423e1dc77e', 'eeceec9f880d4f7eaa7d255655a1a25a', '删除', 'perms[sysMenu:del]', '/sys/menu/del', '2017-04-18 17:10:27', '2017-04-18 17:10:27', NULL, NULL),
('86cae2a4e1764204aa2bbf8bd002ea9f', '14a4ed27e5fb433599a50157b66be691', '保存树', 'perms[sysGoods:savetree]', '/sys/buy/savetree', '2017-09-09 00:58:27', '2017-09-09 00:58:27', NULL, NULL),
('891b5add919f4275b9970ddca0d8804d', 'eeceec9f880d4f7eaa7d255655a1a25a', '树页面', 'perms[sysMenu:tree]', '/sys/menu/tree', '2017-04-18 17:10:27', '2017-04-18 17:10:27', NULL, NULL),
('89c824a34c314585b038b4ce79054e2d', '14a4ed27e5fb433599a50157b66be691', '修改', 'perms[sysGoods:edit]', '/sys/buy/edit', '2017-09-09 00:58:27', '2017-09-09 00:58:27', NULL, NULL),
('8cc234c931174c25968e96248b7fb8fa', '14a4ed27e5fb433599a50157b66be691', '修改页面', 'perms[sysGoods:goedit]', '/sys/buy/goedit', '2017-09-09 00:58:27', '2017-09-09 00:58:27', NULL, NULL),
('8d4a10775fff4ee183295a3d680482e4', '4f4ed019e53b4cd3a5f1c74531197a41', '增加页面', 'perms[sysUser:goadd]', '/sys/user/goadd', '2017-04-18 15:20:54', '2017-04-18 15:20:54', NULL, NULL),
('9066a4192864435b9d19e7278cb967e0', '1f98b20cca794e92a3a349409518ad25', '上传', 'perms[sysDict:download]', '/sys/file/upload', '2017-05-02 10:24:20', '2017-05-02 10:24:20', NULL, NULL),
('918a6331377248218bf8593be510b7b4', 'eeceec9f880d4f7eaa7d255655a1a25a', '保存', 'perms[sysMenu:save]', '/sys/menu/save', '2017-04-18 17:10:27', '2017-04-18 17:10:27', NULL, NULL),
('9231a4419ae14fa89559cbe2302f8aef', '2dcdf7724f8f4d8eaf3c9fce6a0d8e3d', '删除', 'perms[sysFile:del]', '/sys/file/del', '2017-05-02 10:27:13', '2017-05-02 10:27:13', NULL, NULL),
('923d97f34a9748f58044ab838b6fa3fc', '1f98b20cca794e92a3a349409518ad25', '列表', 'perms[sysDict:list]', '/sys/file/list', '2017-05-02 10:24:20', '2017-05-02 10:24:20', NULL, NULL),
('93862e931848401f9097d3f77be7e815', '4dcca247b7134c3ab3156e2dea30860f', '修改', 'perms[sysPerm:edit]', '/sys/perm/edit', '2017-04-19 09:17:14', '2017-04-19 09:17:14', NULL, NULL),
('944fe9ec8b2f4aea93db91b3a566d97f', '14a4ed27e5fb433599a50157b66be691', '查询所有树节点', 'perms[sysGoods:treenodeall]', '/sys/buy/treenodeall', '2017-09-09 00:58:27', '2017-09-09 00:58:27', NULL, NULL),
('967ac38941e244cd9e7298f5a57e2666', '2e3ef8186ff44080897aaa07cbd48adf', '树列表', 'perms[sysBuy:listtree]', '/sys/buy/listtree', '2017-08-21 01:46:30', '2017-08-21 01:46:30', NULL, NULL),
('96d1520a4058430a8072f620c0fecaf8', '1f98b20cca794e92a3a349409518ad25', '树列表', 'perms[sysDict:listtree]', '/sys/file/listtree', '2017-05-02 10:24:20', '2017-05-02 10:24:20', NULL, NULL),
('9a2d64aae4a342209ca619520123c736', '1f98b20cca794e92a3a349409518ad25', '增加', 'perms[sysDict:save]', '/sys/file/save', '2017-05-02 10:24:20', '2017-05-02 10:24:20', NULL, NULL),
('9ec8ea8de44c420eb95bf5a68fd1e875', '2dcdf7724f8f4d8eaf3c9fce6a0d8e3d', '修改', 'perms[sysFile:edit]', '/sys/file/edit', '2017-05-02 10:27:13', '2017-05-02 10:27:13', NULL, NULL),
('9ef5634c9f6149f88999456fb77648a9', '2e3ef8186ff44080897aaa07cbd48adf', '列表', 'perms[sysBuy:list]', '/sys/buy/list', '2017-08-21 01:46:30', '2017-08-21 01:46:30', NULL, NULL),
('9f35fdfa00e441ecb343adca7d7b0807', '1f98b20cca794e92a3a349409518ad25', '修改', 'perms[sysDict:edit]', '/sys/file/edit', '2017-05-02 10:24:20', '2017-05-02 10:24:20', NULL, NULL),
('a4beee06a7c04b8fa392c7f970d7daf2', '6b53d41674374feb9c9fe122c386e62b', '保存', 'perms[sysDict:save]', '/sys/dict/save', '2017-04-20 17:38:03', '2017-04-20 17:38:03', NULL, NULL),
('a58c3c0beb824c2ab2a31ead03ac35e8', 'f153ad366c0c44ce8ab2b66d8a7575b8', '删除', 'perms[sysDict:del]', '/sys/file/del', '2017-05-02 09:59:35', '2017-05-02 09:59:35', NULL, NULL),
('aa71bbec77f3467bbbbb31b4cb71084f', '1f98b20cca794e92a3a349409518ad25', '删除', 'perms[sysDict:del]', '/sys/file/del', '2017-05-02 10:24:20', '2017-05-02 10:24:20', NULL, NULL),
('aa792c41a66f468eae5b3762fcfbf497', '6b53d41674374feb9c9fe122c386e62b', '保存树', 'perms[sysDict:savetree]', '/sys/dict/savetree', '2017-04-20 17:38:03', '2017-04-20 17:38:03', NULL, NULL),
('acb51fadc0704c29a2eddcd500f94ab7', '1e77eaad20c74e1c9898dede322a9a12', '页面', 'perms[sysRole:pages]', '/pages/sys/role/**', '2017-04-19 09:46:31', '2017-04-19 09:46:31', NULL, NULL),
('acda55caa6d1499bac552a79bfb41132', 'f153ad366c0c44ce8ab2b66d8a7575b8', '上传', 'perms[sysDict:download]', '/sys/file/upload', '2017-05-02 09:59:35', '2017-05-02 09:59:35', NULL, NULL),
('b432a46371b5407a8d9392cd62d189ae', '2e3ef8186ff44080897aaa07cbd48adf', '批量删除', 'perms[sysBuy:delall]', '/sys/buy/delall', '2017-08-21 01:46:30', '2017-08-21 01:46:30', NULL, NULL),
('b5ecaa670f7b4f07b8bb96f01c8d9ba9', '43a5e346fb9b49ab8f482a3c9895ef37', '页面', 'perms[sysLeave:pages]', '/pages/sys/leave/**', NULL, NULL, NULL, NULL),
('b8eb75c05449498b8b4a3069efa52daa', '3950eb3e1352457f9d03767b15d5b08e', '页面', 'perms[sysTask:pages]', '/pages/sys/task/**', NULL, NULL, NULL, NULL),
('ba70f014dc6b4f4cb717d2d178bbdab5', '4dcca247b7134c3ab3156e2dea30860f', '批量删除', 'perms[sysPerm:delall]', '/sys/perm/delall', '2017-04-19 09:17:14', '2017-04-19 09:17:14', NULL, NULL),
('bad082c4ca2d47c488f8ef52eadc03db', 'f153ad366c0c44ce8ab2b66d8a7575b8', '页面', 'perms[sysDict:pages]', '/pages/sys/file/**', '2017-05-02 09:59:34', '2017-05-02 09:59:34', NULL, NULL),
('bd427a4fd2c64c1cbb8c0fe544043595', 'eeceec9f880d4f7eaa7d255655a1a25a', '保存树', 'perms[sysMenu:savetree]', '/sys/menu/savetree', '2017-04-18 17:10:27', '2017-04-18 17:10:27', NULL, NULL),
('c165d75d64974443a32143fee40f6f52', '6b53d41674374feb9c9fe122c386e62b', '查询树节点', 'perms[sysDict:treenode]', '/sys/dict/treenode', '2017-04-20 17:38:04', '2017-04-20 17:38:04', NULL, NULL),
('c54024bc903d4ff0b7ccacc22ca16ac3', '1f98b20cca794e92a3a349409518ad25', '修改页面', 'perms[sysDict:goedit]', '/sys/file/goedit', '2017-05-02 10:24:20', '2017-05-02 10:24:20', NULL, NULL),
('c57bfedacb0d4bb2b6cfbb00ea8715ad', 'f153ad366c0c44ce8ab2b66d8a7575b8', '树列表', 'perms[sysDict:listtree]', '/sys/file/listtree', '2017-05-02 09:59:34', '2017-05-02 09:59:34', NULL, NULL),
('c6b73381847c4728a34089fcc7455c13', '4f4ed019e53b4cd3a5f1c74531197a41', '页面', 'perms[sysUser:pages]', '/pages/sys/user/**', '2017-04-18 15:20:54', '2017-04-18 15:20:54', NULL, NULL),
('c6c828011580454e908e5bcb87416b98', '6b53d41674374feb9c9fe122c386e62b', '修改', 'perms[sysDict:edit]', '/sys/dict/edit', '2017-04-20 17:38:03', '2017-04-20 17:38:03', NULL, NULL),
('c6c8dd53a62d41ca8fcfea1d1c0411b9', '1f98b20cca794e92a3a349409518ad25', '上传', 'perms[sysDict:upload]', '/sys/file/upload', '2017-05-02 10:24:20', '2017-05-02 10:24:20', NULL, NULL),
('c82385e9cd4644cb9c5393c280a85d2d', '1e77eaad20c74e1c9898dede322a9a12', '保存', 'perms[sysRole:save]', '/sys/role/save', '2017-04-19 09:46:31', '2017-04-19 09:46:31', NULL, NULL),
('c89bc39427bb46daa90613b5222c7b1e', 'eeceec9f880d4f7eaa7d255655a1a25a', '查询所有树节点', 'perms[sysMenu:treenodeall]', '/sys/menu/treenodeall', '2017-04-18 17:10:27', '2017-04-18 17:10:27', NULL, NULL),
('c9449f278c384dbbacd352affb2cb260', '6b53d41674374feb9c9fe122c386e62b', '删除', 'perms[sysDict:del]', '/sys/dict/del', '2017-04-20 17:38:03', '2017-04-20 17:38:03', NULL, NULL),
('ca19903291e7419ba7a7c4da5e2d9a86', '4dcca247b7134c3ab3156e2dea30860f', '页面', 'perms[sysPerm:pages]', '/pages/sys/perm/**', '2017-04-19 09:17:14', '2017-04-19 09:17:14', NULL, NULL),
('cc0fb413134649dca752d3eb36c66a47', '2dcdf7724f8f4d8eaf3c9fce6a0d8e3d', '树列表', 'perms[sysFile:listtree]', '/sys/file/listtree', '2017-05-02 10:27:12', '2017-05-02 10:27:12', NULL, NULL),
('cc2714fde9fa4fd4967cfb6e006b2777', '4f4ed019e53b4cd3a5f1c74531197a41', '批量删除', 'perms[sysUser:delall]', '/sys/user/delall', '2017-04-18 15:20:55', '2017-04-18 15:20:55', NULL, NULL),
('cd46b5a26bfb4382818e354a14f61b18', '1f98b20cca794e92a3a349409518ad25', '增加页面', 'perms[sysDict:goadd]', '/sys/file/goadd', '2017-05-02 10:24:20', '2017-05-02 10:24:20', NULL, NULL),
('cec77113b4574977b0425d848a5d4d2f', '4f4ed019e53b4cd3a5f1c74531197a41', '修改', 'perms[sysUser:edit]', '/sys/user/edit', '2017-04-18 15:20:55', '2017-04-18 15:20:55', NULL, NULL),
('d17331a9447e4f58b753707c6179cb27', '4dcca247b7134c3ab3156e2dea30860f', '保存树', 'perms[sysPerm:savetree]', '/sys/perm/savetree', '2017-04-19 09:17:14', '2017-04-19 09:17:14', NULL, NULL),
('d1948195d8784fb68361c365565147ce', 'f153ad366c0c44ce8ab2b66d8a7575b8', '批量删除', 'perms[sysDict:delall]', '/sys/file/delall', '2017-05-02 09:59:35', '2017-05-02 09:59:35', NULL, NULL),
('d20c82b7a6484f4f992eb9aa533c06c2', 'eeceec9f880d4f7eaa7d255655a1a25a', '保存页面', 'perms[sysMenu:goadd]', '/sys/menu/goadd', '2017-04-18 17:10:27', '2017-04-18 17:10:27', NULL, NULL),
('d4d35ebbfcfc4fac8dccff3970c5cd61', '2dcdf7724f8f4d8eaf3c9fce6a0d8e3d', '批量删除', 'perms[sysFile:delall]', '/sys/file/delall', '2017-05-02 10:27:13', '2017-05-02 10:27:13', NULL, NULL),
('d51929fe10f64ea19db89c1fc1a52d18', '14a4ed27e5fb433599a50157b66be691', '批量删除', 'perms[sysGoods:delall]', '/sys/buy/delall', '2017-09-09 00:58:27', '2017-09-09 00:58:27', NULL, NULL),
('d5f7e79fbf794482b79cd62717f798db', '1f98b20cca794e92a3a349409518ad25', '批量删除', 'perms[sysDict:delall]', '/sys/file/delall', '2017-05-02 10:24:20', '2017-05-02 10:24:20', NULL, NULL),
('d5f822abaa4b494e80c435710cd62242', 'f153ad366c0c44ce8ab2b66d8a7575b8', '上传', 'perms[sysDict:upload]', '/sys/file/upload', '2017-05-02 09:59:34', '2017-05-02 09:59:34', NULL, NULL),
('d880108bb2374514b09cff4ed35b0f70', '2dcdf7724f8f4d8eaf3c9fce6a0d8e3d', '上传', 'perms[sysFile:download]', '/sys/file/upload', '2017-05-02 10:27:12', '2017-05-02 10:27:12', NULL, NULL),
('d8c4f16457a8473dbf96f82e6c6e9151', 'eeceec9f880d4f7eaa7d255655a1a25a', '批量删除', 'perms[sysMenu:delall]', '/sys/menu/delall', '2017-04-18 17:10:27', '2017-04-18 17:10:27', NULL, NULL),
('db23f33f224e4f7390d8cdae4002c367', '2dcdf7724f8f4d8eaf3c9fce6a0d8e3d', '增加', 'perms[sysFile:save]', '/sys/file/save', '2017-05-02 10:27:12', '2017-05-02 10:27:12', NULL, NULL),
('dc15597f79b749d1b5b2f6fd5208bcb3', '6b53d41674374feb9c9fe122c386e62b', '查询所有树节点', 'perms[sysDict:treenodeall]', '/sys/dict/treenodeall', '2017-04-20 17:38:04', '2017-04-20 17:38:04', NULL, NULL),
('deef91d75c544d26a6cfd2752b44b6cc', '2e3ef8186ff44080897aaa07cbd48adf', '上传', 'perms[sysBuy:download]', '/sys/buy/upload', '2017-08-21 01:46:30', '2017-08-21 01:46:30', NULL, NULL),
('e2f5952b6aae458da93e2d5967e289c7', 'f153ad366c0c44ce8ab2b66d8a7575b8', '修改', 'perms[sysDict:edit]', '/sys/file/edit', '2017-05-02 09:59:35', '2017-05-02 09:59:35', NULL, NULL),
('e34359202b614f9188fc5b67470486ee', 'eeceec9f880d4f7eaa7d255655a1a25a', '删除树节点', 'perms[sysMenu:deltree]', '/sys/menu/deltree', '2017-04-22 00:00:00', '2017-04-18 17:10:27', NULL, NULL),
('e67b215082434ff8bc41d16bc73814e7', '6b53d41674374feb9c9fe122c386e62b', '保存页面', 'perms[sysDict:goadd]', '/sys/dict/goadd', '2017-04-20 17:38:03', '2017-04-20 17:38:03', NULL, NULL),
('e9a8d2d155c049c783a8409e893656e1', '4dcca247b7134c3ab3156e2dea30860f', '查询树节点', 'perms[sysPerm:treenode]', '/sys/perm/treenode', '2017-04-19 09:17:14', '2017-04-19 09:17:14', NULL, NULL),
('edf0d059976f4c9a8c93f8d239634e64', '1e77eaad20c74e1c9898dede322a9a12', '查询所有树节点', 'perms[sysRole:treenodeall]', '/sys/role/treenodeall', '2017-04-19 09:46:32', '2017-04-19 09:46:32', NULL, NULL),
('eeceec9f880d4f7eaa7d255655a1a25a', 'root', '菜单管理', 'perms[sysMenu:all]', '/sys/menu/**', '2017-04-18 17:10:26', '2017-04-18 17:10:26', NULL, NULL),
('f153ad366c0c44ce8ab2b66d8a7575b8', 'root', '用户管理', 'perms[sysDict:all]', '/sys/file/**', '2017-05-02 09:59:34', '2017-05-02 09:59:34', NULL, NULL),
('f1e1138c321c4fabbd3bed90d92738f9', '4dcca247b7134c3ab3156e2dea30860f', '保存页面', 'perms[sysPerm:goadd]', '/sys/perm/goadd', '2017-04-19 09:17:14', '2017-04-19 09:17:14', NULL, NULL),
('f3318bafc23549ba97ca78ddfeb5626e', '4dcca247b7134c3ab3156e2dea30860f', '删除树节点', 'perms[sysPerm:deltree]', '/sys/perm/deltree', '2017-04-19 09:17:14', '2017-04-19 09:17:14', NULL, NULL),
('f41209db28284ca9a937d4faed265def', '1e77eaad20c74e1c9898dede322a9a12', '删除', 'perms[sysRole:del]', '/sys/role/del', '2017-04-19 09:46:31', '2017-04-19 09:46:31', NULL, NULL),
('f423aa88d85c48e3a00312156428e938', '6b53d41674374feb9c9fe122c386e62b', '批量删除', 'perms[sysDict:delall]', '/sys/dict/delall', '2017-04-20 17:38:03', '2017-04-20 17:38:03', NULL, NULL),
('f52823758639410a9c6d54a5e82743d5', '2e3ef8186ff44080897aaa07cbd48adf', '修改', 'perms[sysBuy:edit]', '/sys/buy/edit', '2017-08-21 01:46:30', '2017-08-21 01:46:30', NULL, NULL),
('f613f43cf16d4915bb9d40711e883c0c', '14a4ed27e5fb433599a50157b66be691', '删除', 'perms[sysGoods:del]', '/sys/buy/del', '2017-09-09 00:58:27', '2017-09-09 00:58:27', NULL, NULL),
('f6e2197b47a6429785fb4c1528d83b1d', '2dcdf7724f8f4d8eaf3c9fce6a0d8e3d', '列表', 'perms[sysFile:list]', '/sys/file/list', '2017-05-02 10:27:12', '2017-05-02 10:27:12', NULL, NULL),
('f89644078f6b4f08b5412ec44ab2e982', 'f153ad366c0c44ce8ab2b66d8a7575b8', '修改页面', 'perms[sysDict:goedit]', '/sys/file/goedit', '2017-05-02 09:59:35', '2017-05-02 09:59:35', NULL, NULL),
('fa4d0cac179e44d7b0e1da74b132d9e9', '1f98b20cca794e92a3a349409518ad25', '页面', 'perms[sysDict:pages]', '/pages/sys/file/**', '2017-05-02 10:24:20', '2017-05-02 10:24:20', NULL, NULL),
('fb9217c06607479d8118fafa89628994', '4f4ed019e53b4cd3a5f1c74531197a41', '列表', 'perms[sysUser:list]', '/sys/user/list', '2017-04-18 15:20:54', '2017-04-18 15:20:54', NULL, NULL),
('fc0c9f0a95b24a80a728f34b3d4981f3', '6b53d41674374feb9c9fe122c386e62b', '删除树节点', 'perms[sysDict:deltree]', '/sys/dict/deltree', '2017-04-20 17:38:04', '2017-04-20 17:38:04', NULL, NULL);

-- 
-- Dumping data for table sys_procdef
--

-- Table adminltemy.sys_procdef does not contain any data (it is empty)

-- 
-- Dumping data for table sys_res
--
INSERT INTO sys_res VALUES
('06b6de17314d4316906db34b4c8c8a33', 'root', 'xxxxxxxxxxxxx', '', NULL, NULL, NULL, NULL, NULL),
('08d605af59f6447cb9ed9d78731842f1', 'root', 'xxxxxxxxxxxx', '', NULL, NULL, NULL, NULL, NULL),
('0ccd416d257246d79231d7db876a9075', 'root', 'test', '', NULL, NULL, NULL, NULL, NULL),
('1dd3eecb69814f0db40d76f7d4185fdd', 'root', 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', '', NULL, NULL, NULL, NULL, NULL),
('31a453c233c8447fa39759b8abefc905', '', '', '', NULL, NULL, NULL, NULL, NULL),
('3f4dcf0709c74741a197d75403efb0f9', 'root', 'DDDDDDDDDDD', '', NULL, NULL, NULL, NULL, NULL),
('4b9c7c37534b481684755e02aaa40fd7', '', '', '', NULL, NULL, NULL, NULL, NULL),
('53a3fbe9d0384791b1f9d243487a4922', '', '', '', NULL, NULL, NULL, NULL, NULL),
('54ab7d176cda46c89073a8ad2084b8e3', '5fa1c793831e4c3ea76d538466071ee8', 'asd', '', NULL, NULL, NULL, NULL, NULL),
('5fa1c793831e4c3ea76d538466071ee8', 'root', 'xx', '', NULL, NULL, NULL, NULL, NULL),
('613b490bec144509b0a3cc02f1f47d3d', 'root', 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', '', NULL, NULL, NULL, NULL, NULL),
('6e4e2a5ccee04c85a991b75a7c14f8dd', '', '', '', NULL, NULL, NULL, NULL, NULL),
('88afc7365fb94e0ea73d04a930ada593', 'root', 'asdf', '', NULL, NULL, NULL, NULL, NULL),
('8c03278f94c848b79cf0ed397a30a829', 'root', 'asdf', '', NULL, NULL, NULL, NULL, NULL),
('99c5b0fe171e420389ce8b4793c9fbe8', 'root', 'aaaaaaaaaaaaaaaaaaa', '', NULL, NULL, NULL, NULL, NULL),
('b5ec76178e1b4553947e879dae19461f', '', '', '', NULL, NULL, NULL, NULL, NULL),
('bb9c7d023546426380749e732b28832c', 'root', 'adsf', '', NULL, NULL, NULL, NULL, NULL),
('be6774ff001a4ea097b785f1d29b9f32', 'root', 'adsf', '', NULL, NULL, NULL, NULL, NULL),
('ca0481f406074859a9de0cfafe092221', '0ccd416d257246d79231d7db876a9075', 'testtest', '', NULL, NULL, NULL, NULL, NULL),
('d482851118be4674b09fb386a7bdd02c', '', '', '', NULL, NULL, NULL, NULL, NULL),
('e39aac506e1248acbb4a17aadcb21fde', 'root', 'asdf', '', NULL, NULL, NULL, NULL, NULL),
('f6f3b0334aa646a88f92d059fc9e5ca8', '', '', '', NULL, NULL, NULL, NULL, NULL),
('f81ccfb7af3d49428ba0bf57e13d6d88', '3f4dcf0709c74741a197d75403efb0f9', 'dddd', '', NULL, NULL, NULL, NULL, NULL),
('fdb251b3bcab45afaa315d211b45952f', 'root', 'asffasd', '', NULL, NULL, NULL, NULL, NULL);

-- 
-- Dumping data for table sys_role
--
INSERT INTO sys_role VALUES
('119f86cdcaa44f5ca835946996097f1b', 'root', '1', NULL, NULL, NULL, NULL, NULL, NULL),
('42e8da5208cf4d4da4708272a501ed96', 'root', '管理员', '', NULL, NULL, NULL, NULL, NULL),
('61dab51997f642e3900ed22d500cfdd9', '6632d91267154b608f398405c30c82c4', '二级审批2', '', NULL, NULL, NULL, NULL, NULL),
('6632d91267154b608f398405c30c82c4', 'root', '流程审批', '', NULL, NULL, NULL, NULL, NULL),
('684da94e41ea44a98570bb184a562439', '42e8da5208cf4d4da4708272a501ed96', '超级管理员', '', NULL, NULL, NULL, NULL, NULL),
('7f1617d8111a4daca3d512464b067d7a', '6632d91267154b608f398405c30c82c4', '三级审批', '', NULL, NULL, NULL, NULL, NULL),
('e5296b542fdc4583aa86af5a1de12983', '6632d91267154b608f398405c30c82c4', '一级审批', '', NULL, NULL, NULL, NULL, NULL);

-- 
-- Dumping data for table sys_role_activiti
--
INSERT INTO sys_role_activiti VALUES
('1ae0f3aa1f4f4dc0aa443bbcc7dd045b', 'e5296b542fdc4583aa86af5a1de12983', 'a1a5bae83b734816ae223ef75bb32848', 'selected'),
('4e298f20c55c4367a6086647bb39852d', '61dab51997f642e3900ed22d500cfdd9', '25ec957398e64e138c968804f3c45246', 'partsel'),
('6f5be4f2bec8494caade8baa151a68ac', '61dab51997f642e3900ed22d500cfdd9', '2ec0bc9be8d442c999054024e0954f39', 'selected'),
('95d631285ab447a88d625e70f491788c', '7f1617d8111a4daca3d512464b067d7a', 'da776ffe989a44f5b0a3af9d5983d0aa', 'selected'),
('c60c63d35384429792b9807301ee8284', '7f1617d8111a4daca3d512464b067d7a', '25ec957398e64e138c968804f3c45246', 'partsel'),
('d1b58d7910954603ad0e63311a2a5f73', 'e5296b542fdc4583aa86af5a1de12983', '25ec957398e64e138c968804f3c45246', 'partsel');

-- 
-- Dumping data for table sys_role_menu
--

-- Table adminltemy.sys_role_menu does not contain any data (it is empty)

-- 
-- Dumping data for table sys_role_perm
--

-- Table adminltemy.sys_role_perm does not contain any data (it is empty)

-- 
-- Dumping data for table sys_role_res
--
INSERT INTO sys_role_res VALUES
('a1192f0e19de4226bc9a4fc9778473c4', '55ac34fda1714310824cb7ef5ce38f25', 'bb9c7d023546426380749e732b28832c', NULL, NULL, NULL, NULL, NULL),
('f0ab202a4ec94a64be1910764e325720', '55ac34fda1714310824cb7ef5ce38f25', '99c5b0fe171e420389ce8b4793c9fbe8', NULL, NULL, NULL, NULL, NULL);

-- 
-- Dumping data for table sys_user
--
INSERT INTO sys_user VALUES
('222403f77e8c411388fd7f50c23974e8', '1', '1', '3a3c6ca24f6e565c26100b01b5c3fc91', NULL, NULL, NULL, NULL, NULL, NULL, 'a55c6e261e774082bbd5521130c5c1e6', NULL, NULL, '2017-04-19 15:07:23', '2017-08-14 04:26:36', NULL, 'da8c252c6672450db9a4af267aa5e6ad'),
('da8c252c6672450db9a4af267aa5e6ad', '超人', 'admin', 'be98207ac6d9de9ce8f53ada21922be3', NULL, NULL, '880d185f11794395a9439705eab558e0', '', 'a6a5b5dffe754fd5901698bf10cf2f15', NULL, '37b73a43f23a42edb6bef45a96628217', '', '', NULL, '2017-08-14 04:12:28', NULL, 'da8c252c6672450db9a4af267aa5e6ad'),
('f7860f5facb344159f0907c409e8bb9c', '1', '1', '3a3c6ca24f6e565c26100b01b5c3fc91', NULL, NULL, '3903e4aacde24ecc9bb36868d5b1987a', NULL, 'a6a5b5dffe754fd5901698bf10cf2f15', NULL, NULL, NULL, NULL, '2017-04-21 17:09:29', NULL, 'da8c252c6672450db9a4af267aa5e6ad', NULL);

-- 
-- Dumping data for table sys_user_role
--

-- Table adminltemy.sys_user_role does not contain any data (it is empty)

-- 
-- Dumping data for table act_ge_bytearray
--

-- Table adminltemy.act_ge_bytearray does not contain any data (it is empty)

-- 
-- Dumping data for table act_id_membership
--

-- Table adminltemy.act_id_membership does not contain any data (it is empty)

-- 
-- Dumping data for table act_ru_execution
--

-- Table adminltemy.act_ru_execution does not contain any data (it is empty)

-- 
-- Dumping data for table act_procdef_info
--

-- Table adminltemy.act_procdef_info does not contain any data (it is empty)

-- 
-- Dumping data for table act_re_model
--

-- Table adminltemy.act_re_model does not contain any data (it is empty)

-- 
-- Dumping data for table act_ru_event_subscr
--

-- Table adminltemy.act_ru_event_subscr does not contain any data (it is empty)

-- 
-- Dumping data for table act_ru_job
--

-- Table adminltemy.act_ru_job does not contain any data (it is empty)

-- 
-- Dumping data for table act_ru_task
--

-- Table adminltemy.act_ru_task does not contain any data (it is empty)

-- 
-- Dumping data for table act_ru_variable
--

-- Table adminltemy.act_ru_variable does not contain any data (it is empty)

-- 
-- Dumping data for table act_ru_identitylink
--

-- Table adminltemy.act_ru_identitylink does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;